# Generated by Django 4.2.16 on 2024-09-19 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
